# Generated by Django 5.0.6 on 2024-08-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_investments_investment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='amount_invested',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
